name: infumia_lint
description: A comprehensive custom lint package for Dart and Flutter projects, providing additional static analysis rules to enforce code quality, maintainability, and team coding standards.
version: 1.0.0
repository: https://github.com/infumia/infumia_lint
homepage: https://github.com/infumia/infumia_lint
issue_tracker: https://github.com/infumia/infumia_lint/issues

environment:
  sdk: ">=3.9.2"

dependencies:
  custom_lint: ">=0.8.1"
  custom_lint_builder: ">=0.8.1"
  analyzer: ">=8.4.0"
  analyzer_plugin: ">=0.13.10"
