name: infumia_lint
description: A comprehensive custom lint package for Dart and Flutter projects, providing additional static analysis rules to enforce code quality, maintainability, and team coding standards.
version: 1.0.0
repository: https://github.com/infumia/infumia_lint
homepage: https://github.com/infumia/infumia_lint
issue_tracker: https://github.com/infumia/infumia_lint/issues

environment:
  sdk: ">=3.9.2"

dependencies:
  analyzer: ">=10.0.2"
  analyzer_plugin: ">=0.14.2"

  custom_lint:
    git:
      url: https://github.com/Infumia/dart_custom_lint.git
      path: packages/custom_lint
      ref: 5930d5a1e1bc1a19b53b5d46d6985411d0d84111

  custom_lint_builder:
    git:
      url: https://github.com/Infumia/dart_custom_lint.git
      path: packages/custom_lint_builder
      ref: 5930d5a1e1bc1a19b53b5d46d6985411d0d84111
