name: infumia_lint
description: A comprehensive custom lint package for Dart and Flutter projects, providing additional static analysis rules to enforce code quality, maintainability, and team coding standards.
version: 1.0.0
repository: https://github.com/infumia/infumia_lint
homepage: https://github.com/infumia/infumia_lint
issue_tracker: https://github.com/infumia/infumia_lint/issues

environment:
  sdk: ">=3.9.2"

dependencies:
  analyzer: ">=10.0.0"
  analyzer_plugin: ">=0.14.2"

  custom_lint:
    git:
      url: https://github.com/Infumia/dart_custom_lint.git
      path: packages/custom_lint
      ref: b86cd8569301b9ea817c04469dc9df52070a25cd

  custom_lint_builder:
    git:
      url: https://github.com/Infumia/dart_custom_lint.git
      path: packages/custom_lint_builder
      ref: b86cd8569301b9ea817c04469dc9df52070a25cd
