name: infumia_lint
description: A comprehensive custom lint package for Dart and Flutter projects, providing additional static analysis rules to enforce code quality, maintainability, and team coding standards.
version: 1.0.0
repository: https://github.com/infumia/infumia_lint
homepage: https://github.com/infumia/infumia_lint
issue_tracker: https://github.com/infumia/infumia_lint/issues

environment:
  sdk: ">=3.9.2"

dependencies:
  analyzer: ">=10.0.0"
  analyzer_plugin: ">=0.14.0"

  custom_lint:
    git:
      url: https://github.com/Infumia/dart_custom_lint.git
      path: packages/custom_lint
      ref: 9819835468a7a8603f75a83d18e810431f24af77

  custom_lint_builder:
    git:
      url: https://github.com/Infumia/dart_custom_lint.git
      path: packages/custom_lint_builder
      ref: 9819835468a7a8603f75a83d18e810431f24af77
